---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  labels:
    app: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: aimaraa/workshop-rest-api:latest
        imagePullPolicy: Always
        env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_DATABASE
            value: strapi
          - name: MYSQL_ROOT_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password
                key: password
        ports:
        - containerPort: 80
