---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  labels:
    app: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: aimaraa/workshop-rest-api:latest
        imagePullPolicy: Always
        env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_DATABASE
            value: strapi
          - name: MYSQL_ROOT_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-password
                key: password
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "2"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: strapi
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: hello-app
#     spec:
#       containers:
#         - name: strapi
#           image: aimaraa/workshop-rest-api:latest
#           imagePullPolicy: Always
